openapi: 3.0.3
info:
  title: Cashflo APIs (Internal)
  version: 1.0.0
tags:
  - name: Nova
    description: Platform for managing payments in Cashflo
paths:
  /v1/nova/payout/payment:
    post:
      summary: Create a new payment transaction in Nova
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PaymentTransaction'
            example:
              - senderAccountId: "IN123456789"
                recipientAccountNumber: "9876543210"
                amount: 10.00
                currency: "INR"
                paymentMethod: "bank_transfer"
                referenceId: "PAYOUT_IN_20231025_001"
                recipientDetails:
                  recipientName: "John Doe"
                  bankName: "HDFC Bank"
                  ifscCode: "HDFC0000123"
                  branchName: "Mumbai Branch"
                  bankAddress: "123 Main Street, Mumbai, India"
                paymentCategory:
                  category: "deducation"
                  subCategory: "platformFee"
              - senderAccountId: "IN123456789"
                recipientAccountNumber: "9876543210"
                amount: 1000.00
                currency: "INR"
                paymentMethod: "bank_transfer"
                referenceId: "PAYOUT_IN_20231025_001"
                recipientDetails:
                  recipientName: "John Doe"
                  bankName: "HDFC Bank"
                  ifscCode: "HDFC0000123"
                  branchName: "Mumbai Branch"
                  bankAddress: "123 Main Street, Mumbai, India"
                paymentCategory:
                  category: "payment"
                  subCategory: "invoice"
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              example:
                requestId: "abc12345"
                message: "Transaction created successfully"
        '400':
          description: Bad request, invalid input
          content:
            application/json:
              examples:
                validationError:
                  value:
                    errorCode: "VALIDATION_ERROR"
                    errorMessage: "Invalid input, please check your request payload"
                duplicateRequest:
                  value:
                    errorCode: "DUPLICATE_REQUEST"
                    errorMessage: "Error processing the request. This request has already been processed."
components:
  schemas:
    PaymentTransaction:
      type: object
      properties:
        senderAccountId:
          type: string
        recipientAccountNumber:
          type: string
        amount:
          type: number
          format: double
        currency:
          type: string
        paymentMethod:
          type: string
        referenceId:
          type: string
        recipientDetails:
          $ref: '#/components/schemas/RecipientDetails'
        paymentCategory:
          $ref: '#/components/schemas/PaymentCategory'

    RecipientDetails:
      type: object
      properties:
        recipientName:
          type: string
        bankName:
          type: string
        ifscCode:
          type: string
        branchName:
          type: string
        bankAddress:
          type: string

    PaymentCategory:
      type: object
      properties:
        category:
          type: string
        subCategory:
          type: string
