openapi: 3.0.3
info:
  title: Cashflo APIs (Internal)
  version: 1.0.0
tags:
  - name: Nova
    description: Platform for managing payments in Cashflo
paths:
  /payout/payment-request:
    post:
      summary: Create a new payment request in Nova
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PaymentTransaction'
            examples:
              "valid payload":
                value:
                - requesterAccountId: "IN123456789"
                  amount: 10.00
                  referenceId: "PAYOUT_IN_20231025_001"
                  source: "b2b_payments"
                  recipientDetails:
                    recipientName: "John Doe"
                    ifscCode: "HDFC0000123"
                    bankAccountNumber: "9876543210"
                - requesterAccountId: "IN123456789"
                  amount: 1000.00
                  referenceId: "PAYOUT_IN_20231025_002"
                  source: "b2b_payments"
                  recipientDetails:
                    recipientName: "John Doe"
                    ifscCode: "HDFC0000123"
                    bankAccountNumber: "9876543210"
              
              "invalid payload":
                value:
                - requesterAccountId: "IN123456789"
                  amount: 500.00
                  referenceId: "PAYOUT_IN_20231025_003"
                  source: "b2b_payments"
                  recipientDetails:
                    recipientName: "John Doe"
                    bankAccountNumber: "9876543210"

      responses:
        '200':
          description: "Since validation and rejections are at row level the response is always 200"
          content:
            application/json:
              examples:
                "valid payload":
                  value:
                  - referenceId: "PAYOUT_IN_20231025_001"
                    status: "success"
                    message: "Request created successfully"
                  - referenceId: "PAYOUT_IN_20231025_002"
                    status: "failed"
                    message: "Duplicate reference id"
                "invalid payload":
                  value:
                  - referenceId: "PAYOUT_IN_20231025_002"
                    status: "failed"
                    message: "Invalid request payload"

components:
  schemas:
    PaymentTransaction:
      type: object
      properties:
        requesterAccountId:
          type: string
          description: Buyer account id
        source:
          $ref: '#/components/schemas/PaymentRequestSource'
        amount:
          type: number
          format: double
          description: Amount to be payed out. Max 2 decimal points.
        referenceId:
          type: string
          description: Unique id used for de-duplicating the payment requests
        recipientDetails:
          $ref: '#/components/schemas/RecipientDetails'

    RecipientDetails:
      type: object
      properties:
        recipientName:
          type: string
        ifscCode:
          type: string
        bankAccountNumber:
          type: string

    PaymentRequestSource:
      type: string
      enum:
        - b2b_payments
        - venfin
